

CREATE TABLE IF NOT EXISTS discount (
    id int unique PRIMARY KEY generated by DEFAULT as identity,
    name VARCHAR(255) unique not null,
    volume INT not null,
    threshold INT not null
);

CREATE TABLE customer (
    id int unique PRIMARY KEY generated by DEFAULT as identity,
    name VARCHAR(255) not null,
    phone VARCHAR(255) unique not null,
    discount_id int REFERENCES discount (id),
    order_count NUMERIC(6,2)
);

create table restaurant (
    id int unique PRIMARY KEY generated by DEFAULT as identity,
    name varchar(255) not null,
    address varchar(255) not null,
    work_hours varchar(255) not null
);

create table worker_type (
    id int unique PRIMARY KEY generated by DEFAULT as identity,
    category_name varchar(255) unique
);
create table worker (
    id int unique PRIMARY KEY generated by DEFAULT as identity,
    full_name varchar(255) not null,
    phone_number varchar(13) unique,
    workers_type_id int REFERENCES worker_type (id),
    restaurant_id int REFERENCES restaurant (id)
);

create table product_type (
    id int unique PRIMARY KEY generated by DEFAULT as identity,
    type_name VARCHAR(255) unique not null,
    age_limit BOOLEAN not null,
    parent_product_type_id int null REFERENCES product_type(id)
);

create table product (
    id int unique PRIMARY KEY generated by DEFAULT as identity,
    name VARCHAR(255) UNIQUE not null,
    price NUMERIC(10,2) not null,
    product_type_id int REFERENCES product_type(id)
);

create table orders (
    id int unique PRIMARY KEY generated by DEFAULT as identity,
    datetime TIMESTAMP DEFAULT now(),
    status int not null,
    price NUMERIC(15,2) not null,
    restaurant_id int REFERENCES restaurant (id),
    customer_id int null REFERENCES customer (id),
    waiter_id int REFERENCES worker (id)
);

create table delivery (
    order_id int REFERENCES worker (id),
    address text not null,
    datetime TIMESTAMP DEFAULT now(),
    deliverer_id int primary key REFERENCES orders (id)
);

create table order_menu (
    order_id int REFERENCES orders (id),
    menu_id int REFERENCES product (id),
    count int not null,
    price NUMERIC(10,2) not null,
    cool_id int REFERENCES worker (id)
);
